import VQPresence from './vq-presence.js';
const $=id=>document.getElementById(id),views=['history','search','guide','cycle'];let active=$('history'),run=0,recording=null,lastReport=null;
VQPresence.init({composer:$('composer')});
const report=r=>{if(!r.ok)$('notice').textContent=r.error;return r;};
const sleep=ms=>new Promise(resolve=>{let elapsed=0,last=0;function frame(t){if(!document.hidden&&last)elapsed+=t-last;last=t;if(elapsed>=ms)resolve();else requestAnimationFrame(frame);}requestAnimationFrame(frame);});
async function prepareView(el){const hidden=el.hidden,visibility=el.style.visibility;el.hidden=false;el.style.visibility='hidden';const r=await VQPresence.prepare(el);el.style.visibility=visibility;el.hidden=hidden;return r;}
async function warm(){const results=[];for(const id of views){if(id==='cycle')continue;results.push(await prepareView($(id)));}const view=$('search'),hidden=view.hidden;view.hidden=false;for(const card of view.querySelectorAll('.card'))results.push(await VQPresence.prepare(card));view.hidden=hidden;const ok=results.filter(x=>x.ok).length;$('render-mode').textContent=VQPresence.diagnostics().webgl2?`${ok}/${results.length} SNAPSHOTS READY`:'CSS FALLBACK';window.demoReady=true;return results;}
async function show(id,kind=$('kind').value){run++;VQPresence.clear();if(active===$(id))return {ok:true};const previous=active;active=$(id);return report(await VQPresence.transition({from:previous,to:active,kind,ms:220}));}
async function cycle(missing=false){const token=++run;await VQPresence.unfocus({instant:true});if(missing)VQPresence.clear();const previous=active;active=$('cycle');if(previous!==active)await VQPresence.transition({from:previous,to:active,kind:$('kind').value});$('cycle-cards').replaceChildren();$('cycle-answer').replaceChildren();const requestId='demo-'+token,question=$('prompt').value.trim()||'Find thoughtful films about discovery from this year.';const send=(type,data)=>report(VQPresence.event({type,data:{requestId,...data}}));const pause=async ms=>{await sleep(ms);return token===run;};send('read',{text:question});if(!await pause(350))return;
 if(!missing){const spans=[];for(const [word,role]of [['films','result'],['discovery','topic'],['this year','time']]){const start=question.indexOf(word);if(start>=0)spans.push({start,end:start+word.length,role});}send('intent',{spans});if(!await pause(450))return;send('search',{query:'Discovery films',label:'Searching · fictional demo catalogue'});if(!await pause(400))return;
 for(const s of [{id:'a',domain:'archive.example',title:'An observatory and a question'},{id:'b',domain:'journal.example',title:'New ways of looking'},{id:'c',domain:'cinema.example',title:'A journey beyond the map'},{id:'d',domain:'catalogue.example',title:'An unrelated listing'}]){send('source',{...s,decision:'pending'});if(!await pause(250))return;}
 send('source',{id:'a',domain:'archive.example',title:'An observatory and a question',decision:'kept'});send('source',{id:'b',domain:'journal.example',title:'New ways of looking',decision:'kept'});send('source',{id:'c',domain:'cinema.example',title:'A journey beyond the map',decision:'kept'});send('source',{id:'d',domain:'catalogue.example',title:'An unrelated listing',decision:'discarded'});if(!await pause(400))return;
 for(const [i,title]of ['The Quiet Observatory','Beyond the Frame'].entries()){const el=document.createElement('article');el.className='cycle-card';const h=document.createElement('h3');h.textContent=title;el.append(h);const p=document.createElement('p');p.textContent='Fictional demo selection · '+(i+1);el.append(p);$('cycle-cards').append(el);send('card',{id:'card-'+i,el,phase:'skeleton',rank:i});if(!await pause(250))return;send('card',{id:'card-'+i,el,phase:'ready',rank:i,sourceIds:[i?'b':'a']});}
 }
 const chunks=['Two different ways to follow curiosity. ','The Quiet Observatory rewards patience. ','Beyond the Frame is the stronger match ','if you want a film that challenges how you see evidence.'];for(let i=0;i<chunks.length;i++){send('compose',{el:$('cycle-answer'),delta:chunks[i],sourceIds:missing?[]:[i<2?'a':'b']});if(!missing&&i===2)send('card',{id:'card-1',attention:true});if(!await pause(500))return;}send('done',{});$('notice').textContent=missing?'Only read, compose and done were sent. No sources or searches were invented.':'Scripted log complete · 4 sources, 3 kept. No real web search was performed.';}
$('run-cycle').onclick=()=>cycle();$('explore').onclick=()=>show('search');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('missing').onclick=()=>cycle(true);$('composer').onsubmit=e=>{e.preventDefault();cycle();};$('unfocus').onclick=()=>VQPresence.unfocus();addEventListener('keydown',e=>{if(e.key==='Escape')VQPresence.unfocus();});
for(const c of document.querySelectorAll('.card')){const focus=()=>VQPresence.focus(c,[...document.querySelectorAll('.card')].filter(x=>x!==c));c.onclick=focus;c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();focus();}};}
$('dissolve').onclick=async()=>{if(active!==$('search'))await show('search');const el=document.querySelector('.card');await VQPresence.dissolve(el,'out',{cell:7,ms:180});await sleep(120);await VQPresence.dissolve(el,'in',{cell:7,ms:180});};
$('decode').onclick=async()=>{await show('guide');const el=$('guide').querySelector('h2');VQPresence.invalidate($('guide'));VQPresence.type(el,'Follow the work.',{mode:'decode',speed:100});};
$('sounds').onclick=async()=>{const r=await VQPresence.sound(!VQPresence.sounds);report(r);$('sounds').textContent='Sound: '+(VQPresence.sounds?'on':'off');};
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('record').onclick=async()=>{if(recording){recording.stop();return;}if(!navigator.mediaDevices?.getDisplayMedia||!window.MediaRecorder){$('notice').textContent='Screen capture is unavailable here. Use your device screen recorder.';return;}try{const stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:60},audio:false});const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(x=>MediaRecorder.isTypeSupported(x));const rec=new MediaRecorder(stream,mime?{mimeType:mime}:{}),chunks=[];recording=rec;rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onstop=()=>{download(new Blob(chunks,{type:rec.mimeType}),'vq-presence-'+innerWidth+'x'+innerHeight+'.webm');stream.getTracks().forEach(t=>t.stop());recording=null;$('record').textContent='Record screen';};stream.getVideoTracks()[0].onended=()=>{if(rec.state!=='inactive')rec.stop();};rec.start();$('record').textContent='Stop recording';await showcase();if(rec.state!=='inactive')rec.stop();}catch(e){$('notice').textContent='Recording not started: '+e.message;}};
async function showcase(){await show('history');for(const kind of ['iris','pixel','scan','glitch','fold']){await sleep(500);await show(active===$('search')?'guide':'search',kind);}await show('search','scan');await VQPresence.focus(document.querySelectorAll('.card')[1],[document.querySelectorAll('.card')[0],document.querySelectorAll('.card')[2]]);await sleep(1200);await VQPresence.unfocus();await cycle();await sleep(1200);await cycle(true);await sleep(1200);await show('history','iris');}
async function benchmark(){const results=[];run++;VQPresence.clear();await VQPresence.unfocus({instant:true});for(const kind of ['iris','pixel','scan','glitch','fold']){const frames=[],start=performance.now();let running=true,last=0;const tick=t=>{if(last)frames.push(t-last);last=t;if(running)requestAnimationFrame(tick);};requestAnimationFrame(tick);let response,backend;for(let i=0;i<6;i++){const to=active===$('search')?$('guide'):$('search'),before=performance.now(),p=VQPresence.transition({from:active,to,kind,ms:220});if(response===undefined)response=performance.now()-before;active=to;backend=(await p).backend;}running=false;frames.sort((a,b)=>a-b);results.push({kind,backend,frames:frames.length,elapsedMs:performance.now()-start,synchronousResponseMs:response,meanFrameMs:frames.reduce((a,b)=>a+b,0)/frames.length,p95FrameMs:frames[Math.floor(frames.length*.95)]});}
 lastReport={at:new Date().toISOString(),viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,userAgent:navigator.userAgent,physicalPhone:'not verified; record device model separately',capture:'prepare completed before timing',results,diagnostics:VQPresence.diagnostics()};return lastReport;}
$('metrics').onclick=async()=>{$('notice').textContent='Measuring 30 view changes…';await benchmark();$('metrics-text').textContent=JSON.stringify(lastReport,null,2);$('dialog').hidden=false;$('notice').textContent='Results are local. Download them to include in your device report.';};$('close-dialog').onclick=()=>$('dialog').hidden=true;$('download-metrics').onclick=()=>{if(lastReport)download(new Blob([JSON.stringify(lastReport,null,2)],{type:'application/json'}),'presence-timings-'+innerWidth+'x'+innerHeight+'.json');};
window.VQDemo={show,cycle,showcase,benchmark,warm};warm();
